"""empty message

Revision ID: 1bd0007eaa35
Revises: 5d74e3cad6be
Create Date: 2021-08-19 18:15:19.994784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bd0007eaa35'
down_revision = '5d74e3cad6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    op.drop_table('awards')
    op.drop_table('certificated')
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('project_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('project_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('project_start_date', mysql.DATETIME(), nullable=True),
    sa.Column('project_end_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='project_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('certificated',
    sa.Column('cert_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificated_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('certificated_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('certificated_achieve_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='certificated_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cert_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('awards',
    sa.Column('awadrd_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('award_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('award_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='awards_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('awadrd_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('education',
    sa.Column('edu_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('school_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('education', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='education_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edu_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
