"""empty message

Revision ID: 352060b34d4d
Revises: fd7fcda283d6
Create Date: 2021-08-19 17:56:35.478150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '352060b34d4d'
down_revision = 'fd7fcda283d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('awadrd_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('award_name', sa.String(length=20), nullable=True),
    sa.Column('award_detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('awadrd_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('certificated',
    sa.Column('cert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('certificated_name', sa.String(length=20), nullable=True),
    sa.Column('certificated_detail', sa.String(length=255), nullable=True),
    sa.Column('certificated_achieve_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('cert_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('education',
    sa.Column('edu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('edu_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=20), nullable=True),
    sa.Column('project_detail', sa.String(length=255), nullable=True),
    sa.Column('project_start_date', sa.DateTime(), nullable=True),
    sa.Column('project_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_collate='utf8_general_ci'
    )
    op.drop_table('racerAwards')
    op.drop_table('racerEducation')
    op.drop_table('racerCertificated')
    op.drop_table('racerProject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racerProject',
    sa.Column('project_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('project_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('project_start_date', mysql.DATETIME(), nullable=True),
    sa.Column('project_end_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='racerproject_ibfk_1'),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('racerCertificated',
    sa.Column('cert_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificated_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('certificated_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('certificated_achieve_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='racercertificated_ibfk_1'),
    sa.PrimaryKeyConstraint('cert_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('racerEducation',
    sa.Column('edu_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('school_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('education', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='racereducation_ibfk_1'),
    sa.PrimaryKeyConstraint('edu_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('racerAwards',
    sa.Column('awadrd_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('award_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('award_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], name='racerawards_ibfk_1'),
    sa.PrimaryKeyConstraint('awadrd_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('project')
    op.drop_table('education')
    op.drop_table('certificated')
    op.drop_table('awards')
    # ### end Alembic commands ###
