"""empty message

Revision ID: 5d74e3cad6be
Revises: f744281a8769
Create Date: 2021-08-19 18:09:10.696851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d74e3cad6be'
down_revision = 'f744281a8769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racers', sa.Column('token', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racers', 'token')
    # ### end Alembic commands ###
