"""empty message

Revision ID: bf4dfd70be57
Revises: c338f00e170f
Create Date: 2021-08-20 13:05:47.472799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf4dfd70be57'
down_revision = 'c338f00e170f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', sa.Column('racer_id', sa.Integer(), nullable=False))
    op.drop_constraint('awards_ibfk_1', 'awards', type_='foreignkey')
    op.create_foreign_key(None, 'awards', 'racers', ['racer_id'], ['racer_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('awards', 'racer_no')
    op.add_column('certificates', sa.Column('racer_id', sa.Integer(), nullable=False))
    op.drop_constraint('certificates_ibfk_1', 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'racers', ['racer_id'], ['racer_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('certificates', 'racer_no')
    op.add_column('educations', sa.Column('racer_id', sa.Integer(), nullable=False))
    op.drop_constraint('educations_ibfk_1', 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'racers', ['racer_id'], ['racer_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('educations', 'racer_no')
    op.add_column('projects', sa.Column('racer_id', sa.Integer(), nullable=False))
    op.drop_constraint('projects_ibfk_1', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'racers', ['racer_id'], ['racer_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('projects', 'racer_no')
    op.drop_column('racers', 'racer_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racers', sa.Column('racer_no', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('projects', sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_ibfk_1', 'projects', 'racers', ['racer_no'], ['racer_no'], ondelete='CASCADE')
    op.drop_column('projects', 'racer_id')
    op.add_column('educations', sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key('educations_ibfk_1', 'educations', 'racers', ['racer_no'], ['racer_no'], ondelete='CASCADE')
    op.drop_column('educations', 'racer_id')
    op.add_column('certificates', sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key('certificates_ibfk_1', 'certificates', 'racers', ['racer_no'], ['racer_no'], ondelete='CASCADE')
    op.drop_column('certificates', 'racer_id')
    op.add_column('awards', sa.Column('racer_no', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'awards', type_='foreignkey')
    op.create_foreign_key('awards_ibfk_1', 'awards', 'racers', ['racer_no'], ['racer_no'], ondelete='CASCADE')
    op.drop_column('awards', 'racer_id')
    # ### end Alembic commands ###
