"""empty message

Revision ID: c338f00e170f
Revises: 6411337480e8
Create Date: 2021-08-20 03:32:24.882411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c338f00e170f'
down_revision = '6411337480e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('award_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('award_name', sa.String(length=20), nullable=True),
    sa.Column('award_detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('award_id'),
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('awards')
    # ### end Alembic commands ###
