"""empty message

Revision ID: fd7fcda283d6
Revises: 
Create Date: 2021-08-18 02:35:35.074423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7fcda283d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racers',
    sa.Column('racer_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_id', sa.String(length=20), nullable=False),
    sa.Column('racer_pw', sa.String(length=255), nullable=False),
    sa.Column('racer_name', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=2048), nullable=True),
    sa.Column('introduce', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('racer_no'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('racerAwards',
    sa.Column('awadrd_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('award_name', sa.String(length=20), nullable=True),
    sa.Column('award_detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('awadrd_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('racerCertificated',
    sa.Column('cert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('certificated_name', sa.String(length=20), nullable=True),
    sa.Column('certificated_detail', sa.String(length=255), nullable=True),
    sa.Column('certificated_achieve_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('cert_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('racerEducation',
    sa.Column('edu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('edu_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('racerProject',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('racer_no', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=20), nullable=True),
    sa.Column('project_detail', sa.String(length=255), nullable=True),
    sa.Column('project_start_date', sa.DateTime(), nullable=True),
    sa.Column('project_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['racer_no'], ['racers.racer_no'], ),
    sa.PrimaryKeyConstraint('project_id'),
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racerProject')
    op.drop_table('racerEducation')
    op.drop_table('racerCertificated')
    op.drop_table('racerAwards')
    op.drop_table('racers')
    # ### end Alembic commands ###
